name: Bug report
description: Create a report to help us improve Router
labels: 'bug'
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Steps to reproduce
      description: |
        Steps to reproduce the problem.
      placeholder: |
        For example:
        1. Enable plugin '...'
        2. Click on the '...' button
        3. See error
  - type: textarea
    validations:
      required: true
    attributes:
      label: Expected behavior
      description: A brief description of what should happen.
  - type: textarea
    attributes:
      label: Screenshots and recordings
      description: |
        If applicable, add screenshots to help explain your problem
  - type: input
    validations:
      required: true
    attributes:
      label: Router
      description: What version of the library are you using?
      placeholder: e.g. 1.0.0
  - type: input
    validations:
      required: true
    attributes:
      label: Browser
      description: Which browser and which version are you using?
      placeholder: e.g. Chrome 92
  - type: input
    validations:
      required: true
    attributes:
      label: OS
      placeholder: e.g. macOS 11.5.2
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here. This can be providers, plugins, custom settings...
